Make Sure `KeyError` is Thrown
hubmapconsortium/portal-visualization pull request #49
Opened 2022-05-24 07:41 UTC by ilan-gold

Just calling `zarr.open` yields a special `zarr` error so I think this is more robust.

2022-05-24 14:03 UTC, mccalluc requested changes
Thanks. Some stylistic suggestions... but skip the first two, and just look at the last: I'd suggest getting rid of the try-except.

This is related to https://github.com/hubmapconsortium/portal-ui/pull/2656 ?

2022-05-24 14:09 UTC, ilan-gold commented on src/portal_visualization/builders/anndata_builders.py
>              gene_alias = None
Ok!

2022-05-24 18:08 UTC, ilan-gold commented
@mccalluc Re-requesting review but I noticed something:
<img width="614" alt="Screen Shot 2022-05-24 at 8 05 42 PM" src="https://user-images.githubusercontent.com/43999641/170103166-5c2291ed-130b-4aed-9984-81630ea28211.png">
The marker genes are hardcoded ENSEMBL IDs.  We should ask Nils what he wants to do about this.

2022-05-25 00:51 UTC, ngehlenborg commented
How are the marker genes hardcoded as Ensembl IDs? Do you meant they are provided only as Ensembl IDs?

If so, it should be possible to use the mapping in the annData store to look up the corresponding gene symbols. If there is no corresponding gene symbol, we should fall back on the Ensembl ID (or use whatever other mechanism we will have in place for Ensembl IDs that are not mapped to gene symbols.

2022-05-25 11:25 UTC, ilan-gold commented
@ngehlenborg When I said hardcoded, I meant that we really can't translate them.  In theory we could map this, but we would need to create a mechanism in Vitessce that does "take factors i.e annotations of cells and if they are gene ids, try to look up the translation in the AnnData field we passed in" - I don't think this is something we want to implement but maybe @keller-mark has a better idea.

2022-05-25 11:34 UTC, ngehlenborg commented
Ok. Let's leave the marker gene annotations as is but switch everything else over to gene symbols. Re-processing of RNA-seq data might never happen given the big backlog of unprocessed data.

2022-05-25 12:41 UTC, mccalluc reviewed
@ilan-gold -- Can you give me the UUID of a dataset I can try with this, and then flag me for review again? I'll use the CLI here to preview it -- I just don't want to be going back and forth between here and the portal.

2022-05-25 13:46 UTC, ilan-gold commented
@mccalluc The two datasets you commented on in the issue should work great - one is missing the HUGO ID's (the first one) and the second has them.  They should both work and not error out, but only one (the second) should have HUGO ID's.

2022-05-25 20:26 UTC, ilan-gold commented
@mccalluc i think those are just ENSEMBL IDs missing a translation so we fall back to those ones

2022-05-25 20:31 UTC, ngehlenborg commented
As it should be!

On May 25, 2022, at 4:26 PM, Ilan Gold ***@***.***> wrote:

﻿

@mccalluc<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mccalluc&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=-zahbihG7P2H0fiPo3RTqce9mFyFku-NJy5aRYNyUSA&m=6yuHYxRBJV5BXWFN3xVc8wYchBLjgfaoUCHCI4qJxlgHKTgREV5SR-uwqkghEp5L&s=G5Imvk0Ir0DSzYGJg3vPAzY2ft398jt-V50Xw9SXwFY&e=> i think those are just ENSEMBL IDs missing a translation so we fall back to those ones

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hubmapconsortium_portal-2Dvisualization_pull_49-23issuecomment-2D1137815896&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=-zahbihG7P2H0fiPo3RTqce9mFyFku-NJy5aRYNyUSA&m=6yuHYxRBJV5BXWFN3xVc8wYchBLjgfaoUCHCI4qJxlgHKTgREV5SR-uwqkghEp5L&s=KvYIAnQJv3HGlrz_SzLhh3U5GHw14seJ2g_91g054is&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAJJABVJV4R3PWHGN2XI6O3VL2EI7ANCNFSM5WYSDGQA&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=-zahbihG7P2H0fiPo3RTqce9mFyFku-NJy5aRYNyUSA&m=6yuHYxRBJV5BXWFN3xVc8wYchBLjgfaoUCHCI4qJxlgHKTgREV5SR-uwqkghEp5L&s=RLAaS5ur-l_FBJWge8Xb2YeOixoBAlkpzVezIFvUIXY&e=>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-06-09 06:54 UTC, merged